version: '1'
services:
  gobii-web-node:
    image: gadm01/gobii_web_vanilla_2c
    ports:
      - "8081:8080"
    command: start.sh
  gobii-db-node:
    image: gadm01/gobii_db_vanilla_2c
    environment:
        - 
    volumes:  
      - 
    ports:
      - "5433:5432"
  gobii-compute-node:
    image: gadm01/gobii_compute_vanilla_2c
    environment:
      - 
volumes:
  data:
    external: false