version: '3'
services:
  web:
    image: gadm01/gobii_web_vanilla_2c:release-2.1-1
    container_name: gobii-web-node
    ports:
      - "8081:8080"
    #command: start.sh
    depends_on:
      - "db"
  db:
    image: gadm01/gobii_db_vanilla_2c:release-2.1-1
    container_name: gobii-db-node
    #environment:
    #    - 
    #volumes:  
    #  - 
    ports:
      - "5433:5432"
  compute:
    container_name: gobii-compute-node
    image: gadm01/gobii_compute_vanilla_2c:release-2.1-1
    #environment:
    #  - 
  loader:
    container_name: gobii-loader-ui
    image: plantandfood/gobii.loader.ui:qa
    ports:
      - "4200:4200"
    environment:
      - PORT: "4200"
      - HOST: "localhost"
      - BASEURL: "gobii-web-node:8080"
volumes:
  data:
    external: false