version: '3'
networks:
  gobii-net:
services:
  # web:
  #   image: gadm01/gobii_web_${IMAGE_SUFFIX}:${GOBII_TAG}
  #   container_name: gobii-web-node
  #   ports:
  #     - "8081:8080"
  #   networks:
  #     - gobii-net
  #   #command: start.sh
  #   depends_on:
  #     - "db"
  # db:
  #   image: gadm01/gobii_db_${IMAGE_SUFFIX}:${GOBII_TAG}
  #   container_name: gobii-db-node
  #   ports:
  #     - "5433:5432"
  #   networks:
  #     - gobii-net
  #   #environment:
  #   #    - 
  #   #volumes:  
  #   #  - 
  # compute:
  #   container_name: gobii-compute-node
  #   image: gadm01/gobii_compute_${IMAGE_SUFFIX}:${GOBII_TAG}
  #   networks:
  #     - gobii-net
  #   #environment:
  #   #  - 
  # loader:
  #   container_name: gobii-loader-ui
  #   image: gadm01/gobii.loader.ui:${LOADER_TAG}
  #   ports:
  #     - "4200:4200"
  #   networks:
  #     - gobii-net
  #   depends_on:
  #     - "web"
  #     - "keycloak"
  #   environment:
  #     PORT: "4200"
  #     HOST: "localhost"
  #     BASEURL: "gobii-web-node:8080"
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:${KEYCLOAK_TAG}
    ports:
      - "8080:8080"
    networks:
      - gobii-net
    volumes:
      # Expecting to have the gobii.keycloak repo checked out besides this one. 
      # Empty dir created and theme ignored if missing.
      - ./../gobii.keycloak/themes/gobii/:/opt/jboss/keycloak/themes/gobii/
    environment:
      KEYCLOAK_PASSWORD: "admin"
      KEYCLOAK_USER: "admin"
    command:
    - -b 0.0.0.0 --server-config=standalone.xml
volumes:
  data:
    external: false