version: '3'
services:
  gobii-web-node:
    image: gadm01/gobii_web_vanilla_2c:release-2.1-1
    container_name: gobii-web-node
    ports:
      - "8081:8080"
    #command: start.sh
  gobii-db-node:
    image: gadm01/gobii_db_vanilla_2c:release-2.1-1
    container_name: gobii-db-node
    #environment:
    #    - 
    #volumes:  
    #  - 
    ports:
      - "5433:5432"
  gobii-compute-node:
    container_name: gobii-compute-node
    image: gadm01/gobii_compute_vanilla_2c:release-2.1-1
    #environment:
    #  - 
volumes:
  data:
    external: false