version: '3'
networks:
  gobii-net:
services:
  db:
    build: ./gobii-db
    container_name: gobii-db-node
    ports:
      - "5433:5432"
    networks:
      - gobii-net
    environment:
      - gobiiuid=${GOBII_UID}
      - gobiigid=${GOBII_GID}
      - gobiiuserpassword=${DOCKER_GOBII_ADMIN_PASSWORD}
    volumes:  
      - ${DATA_DIR}:/data
      - ${NDD_PATH}:/ndd_data
      - tmp_data:/tmp_data
      - gobiipostgresetcubuntu:/etc/postgresql
      - gobiipostgreslogubuntu:/var/log/postgresql
      - gobiipostgreslibubuntu:/var/lib/postgresql
    stdin_open: true
    tty: true
volumes:
  gobiipostgresetcubuntu:
    external: false
  gobiipostgreslogubuntu:
    external: false
  gobiipostgreslibubuntu:
    external: false
  tmp_data:
    external: false